package entity;
// Generated Oct 14, 2018 8:42:03 AM by Hibernate Tools 4.3.1



/**
 * Room generated by hbm2java
 */
public class Room  implements java.io.Serializable {


     private Integer id;
     private String roomNo;
     private String book;
     private String roomType;
     private double price;
     private String RUrl;
     private double discount;
     private String description;

    public Room() {
    }

    public Room(String roomNo, String book, String roomType, double price, String RUrl, double discount, String description) {
       this.roomNo = roomNo;
       this.book = book;
       this.roomType = roomType;
       this.price = price;
       this.RUrl = RUrl;
       this.discount = discount;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }
    public String getBook() {
        return this.book;
    }
    
    public void setBook(String book) {
        this.book = book;
    }
    public String getRoomType() {
        return this.roomType;
    }
    
    public void setRoomType(String roomType) {
        this.roomType = roomType;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public String getRUrl() {
        return this.RUrl;
    }
    
    public void setRUrl(String RUrl) {
        this.RUrl = RUrl;
    }
    public double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(double discount) {
        this.discount = discount;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


