package entity;
// Generated Oct 14, 2018 8:42:03 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private String uname;
     private String pass;
     private String role;
     private String fullname;
     private String UEmail;
     private Date URegDate;

    public User() {
    }

    public User(String uname, String pass, String role, String fullname, String UEmail, Date URegDate) {
       this.uname = uname;
       this.pass = pass;
       this.role = role;
       this.fullname = fullname;
       this.UEmail = UEmail;
       this.URegDate = URegDate;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getUEmail() {
        return this.UEmail;
    }
    
    public void setUEmail(String UEmail) {
        this.UEmail = UEmail;
    }
    public Date getURegDate() {
        return this.URegDate;
    }
    
    public void setURegDate(Date URegDate) {
        this.URegDate = URegDate;
    }




}


